
Public Class ArtHelpProvider
    Inherits HelpDataProvider
    Implements IHelpProvider

    Public Function GetHelpText(code As String) As String Implements IHelpProvider.GetHelpText
        Return GetHelpTextWithUsage(code, ArtHelp, ArtTypes)
    End Function

    Private Shared ArtHelp As New Dictionary(Of String, String) From {{"Cameo", "指定该单位使用哪个SHP文件作为图标（就是你点的那个东西来建造它）。如果该对象没有图标， 游戏默认使用""Missing " + vbCrLf +
"Cameo""图标作为它的图标（就是那个红警2样的图标）。每个图标都必须是SHP格式，并且调色盘要求是红警2的cameo.pal文件。另外，图标的大小要求是60*48像素，即宽60像素，高48像素。"},
{"AltCameo", "指定当该单位升级之后使用的图标。升级是指玩家使用间谍渗透对方的兵营或战车工厂之后，单位所产生的变化。规则和Cameo=标签相同。"},
{"Voxel", "指定该单位的图像是否是vxl（就是说这个单位是不是使用vxl文件作为图形）。游戏会将它和SHP文件区分对待。某些标签是否起作用取决于这个标签是否设置为""yes""（就是说如果这个标签决定某些涉及vxl的标签是否有效。假如被设置成""no""，那么即使你为那些有关vxl的标签赋了值也无效）。"},
{"Remapable", "如果被赋值为yes，那么它将告诉游戏该单位的图像文件（SHP或者VXL）包含特殊的红色像素，这些特殊的红色像素会自动变色为玩家拥有的颜色（就是说如果这个标签赋值yes，那么该单位的图像中采用了特殊红色像素的部分会变成你选择的颜色）。这些特殊的像素位于unittem.pal、unitsno.pal和uniturb.pal这几个调色盘文件中，索引号为16至31。 动画无主，动画上的这个颜色不会被替换"},
{"Normalized", "决定是否调节该对象的动画使之以一个恒定的速度播放。只用于建筑，因为步兵和战车不可能使用动画。即使调用动画，动画也是以动画而非单位的形式出现。"},
{"NewTheater", "如果被赋值为yes，那么该单位（一般是建筑）将会在不同的场景中使用不同的图形（例如温和气候场景和雪地场景）。游戏通过判断图像文件名的第二个字母来决定使用哪个图像。如果某个建筑名叫""[GARADR]""，那么当建筑在雪地场景中建造的时候，游戏会寻找名叫""garadr.shp""的文件作为图像；当建筑在温和气候场景中建造的时候，则寻找""gtradr.shp""。注意A代表雪地气候，U代表城市场景，T代表温和气候场景。尤里的复仇中，D代表沙漠场景，L代表月球场景。如果游戏找不到与场景相关的图像，那么将默认使用文件名第二个字母为G的图像（也就是普通的场景）。"},
{"ShadowIndex", "仅用于使用vxl图像的对象，并且包含多个vxl的对象。它决定了哪个vxl会渲染出单位的影子。例如： 直升机，直升机的机体大概包含两个vxl，即机身和螺旋桨。ShadowIndex=决定了游戏到底是绘制机身的影子还是螺旋桨的影子。"},
{"DemandLoad", "可以被赋值为true或者false。如果设置成true，游戏将会在装载""Loading…""那个画面的时候预载入图像而不是在建造的载入图像。一般用于平民建筑。（这是当然的！你要是打算在那个""Loading…""画面的时候悠哉悠哉地洗个澡的话，就随便你设置……）"},
{"TurretOffset", "指定单位的炮塔位于什么地方，沿着单位的中轴线。换句话说，炮塔距离前后有多远。默认值为0（正中心），单位是""lepton""，其中，256个lepton等于一格。就是说如果某个机体前后长度为1格，相当于前后256个lepton。"},
{"PrimaryFireFLH", "决定了主武器炮弹出膛位置和开火动画播放位置，单位是lepton，格式是(数字英文逗号数字英文逗号数字)，分别表示前，左，高。如果武器的burst=大于1，第二发炮弹会从F -L H的位置发出。"},
{"SecondaryFireFLH", "决定了副武器炮弹出膛位置和开火动画播放位置，单位是lepton，格式是(数字英文逗号数字英文逗号数字)，分别表示前，左，高。如果武器的burst=大于1，第二发炮弹会从F -L H的位置发出。"},
{"ElitePrimaryFireFLH", "决定了精英主武器炮弹出膛位置和开火动画播放位置，单位是lepton，格式是(数字英文逗号数字英文逗号数字)，分别表示前，左，高。如果武器的burst=大于1，第二发炮弹会从F -L H的位置发出。"},
{"EliteSecondaryFireFLH", "决定了精英副武器炮弹出膛位置和开火动画播放位置，单位是lepton，格式是(数字英文逗号数字英文逗号数字)，分别表示前，左，高。如果武器的burst=大于1，第二发炮弹会从F -L H的位置发出。"},
{"AlternateFLH0", "用于大脑车和要塞。决定了炮弹出膛位置和开火动画播放位置，单位是lepton，格式是(数字英文逗号数字英文逗号数字)，分别表示前，左，高。如果武器的burst=大于1，第二发炮弹会从F -L H的位置发出。npext中有新的用法，见ext说明书"},
{"AlternateFLH1", "用于大脑车和要塞。决定了炮弹出膛位置和开火动画播放位置，单位是lepton，格式是(数字英文逗号数字英文逗号数字)，分别表示前，左，高。如果武器的burst=大于1，第二发炮弹会从F -L H的位置发出。npext中有新的用法，见ext说明书"},
{"AlternateFLH2", "用于大脑车和要塞。决定了炮弹出膛位置和开火动画播放位置，单位是lepton，格式是(数字英文逗号数字英文逗号数字)，分别表示前，左，高。如果武器的burst=大于1，第二发炮弹会从F -L H的位置发出。npext中有新的用法，见ext说明书"},
{"AlternateFLH3", "用于大脑车和要塞。决定了炮弹出膛位置和开火动画播放位置，单位是lepton，格式是(数字英文逗号数字英文逗号数字)，分别表示前，左，高。如果武器的burst=大于1，第二发炮弹会从F -L H的位置发出。npext中有新的用法，见ext说明书"},
{"AlternateFLH4", "用于大脑车和要塞。决定了炮弹出膛位置和开火动画播放位置，单位是lepton，格式是(数字英文逗号数字英文逗号数字)，分别表示前，左，高。如果武器的burst=大于1，第二发炮弹会从F -L H的位置发出。npext中有新的用法，见ext说明书"},
{"Weapon0FLH", "第0个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon1FLH", "第1个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon2FLH", "第2个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon3FLH", "第3个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon4FLH", "第4个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon5FLH", "第5个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon6FLH", "第6个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon7FLH", "第7个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon8FLH", "第8个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon9FLH", "第9个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon10FLH", "第10个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon11FLH", "第11个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon12FLH", "第12个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon13FLH", "第13个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon14FLH", "第14个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon15FLH", "第15个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon16FLH", "第16个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon17FLH", "第17个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon18FLH", "第18个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon19FLH", "第19个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon20FLH", "第20个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon21FLH", "第21个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon22FLH", "第22个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon23FLH", "第23个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon24FLH", "第24个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon25FLH", "第25个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon26FLH", "第26个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon27FLH", "第27个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon28FLH", "第28个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon29FLH", "第29个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon30FLH", "第30个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon31FLH", "第31个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon32FLH", "第32个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon33FLH", "第33个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon34FLH", "第34个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon35FLH", "第35个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon36FLH", "第36个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon37FLH", "第37个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon38FLH", "第38个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon39FLH", "第39个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon40FLH", "第40个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon41FLH", "第41个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon42FLH", "第42个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon43FLH", "第43个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon44FLH", "第44个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon45FLH", "第45个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon46FLH", "第46个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon47FLH", "第47个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon48FLH", "第48个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon49FLH", "第49个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon50FLH", "第50个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon51FLH", "第51个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon52FLH", "第52个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon53FLH", "第53个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon54FLH", "第54个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon55FLH", "第55个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon56FLH", "第56个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon57FLH", "第57个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon58FLH", "第58个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon59FLH", "第59个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon60FLH", "第60个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon61FLH", "第61个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon62FLH", "第62个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon63FLH", "第63个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon64FLH", "第64个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon65FLH", "第65个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon66FLH", "第66个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon67FLH", "第67个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon68FLH", "第68个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon69FLH", "第69个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon70FLH", "第70个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon71FLH", "第71个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon72FLH", "第72个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon73FLH", "第73个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon74FLH", "第74个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon75FLH", "第75个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon76FLH", "第76个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon77FLH", "第77个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon78FLH", "第78个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon79FLH", "第79个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon80FLH", "第80个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon81FLH", "第81个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon82FLH", "第82个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon83FLH", "第83个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon84FLH", "第84个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon85FLH", "第85个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon86FLH", "第86个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon87FLH", "第87个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon88FLH", "第88个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon89FLH", "第89个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon90FLH", "第90个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon91FLH", "第91个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon92FLH", "第92个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon93FLH", "第93个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon94FLH", "第94个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon95FLH", "第95个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon96FLH", "第96个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon97FLH", "第97个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon98FLH", "第98个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Weapon99FLH", "第99个武器的开火动画位置。这个标签仅用于拥有多种武器的单位，如ifv，盖特。光棱用的是weapon1，所以也是这个系统。总之，primaryfireflh只对primary有效，weaponxflh只 对weaponx有效。art要和rules的武器代码对应"},
{"Sequence", "决定需要的动画帧是哪一个序列片断头。序列是指定哪些帧用于开火，哪些帧用于行走等等。""Sequence=""决定使用哪一个动作序列作为步兵的SHP图像。更多信息请参见Infantry Sequences部分。"},
{"FireUp", "指定使用第一武器开火的动画的帧的序号。它用来确定例如使用步枪的时候，当你可以看到步枪开火时子弹离开的那一帧的帧序号，不是前一帧也不是后一帧（总之就是那一帧）。仅适用于步兵站着而不是卧倒时。"},
{"FireProne", "指定使用第一武器卧倒开火的动画的帧的序号。它用来确定例如使用步枪的时候，当你可以看到步枪开火时子弹离开的那一帧的帧序号，不是前一帧也不是后一帧（总之就是那一帧）。仅适用于步兵站着而不是卧倒时。"},
{"SecondaryFire", "与""FireUp=""相同，只不过这里是第二武器。"},
{"SecondaryProne", "卧倒用第二武器开火的动画的帧的序号"},
{"Crawls", "指定是否单位能够爬行（包括卧倒）。当然步兵的动作序列必须具有爬行的帧。"},
{"WalkFrames", "指定这个SHP战车（不是使用vxl的战车）每个方向的帧数。假定全方向的动画都存在。这些帧在该SHP战车移动的时候发挥作用。（这种SHP战车和步兵非常类似。）"},
{"FiringFrames", "同上。只不过这些帧用于SHP战车开火。"},
{"Trailer", "这个标签指定哪一个动画被用作尾烟。单位会不停产生动画，动画独立播放，因为单位不停飞远，看起来就是连续的。只对aircraft类单位有效 。对动画也适用。"},
{"SpawnDelay", "每隔多少帧产生一个新的尾烟动画"},
{"UseLineTrail", "使游戏绘制一条跟从与之相关联的对象的线，就像轨迹一样。限制和""Trailer=""一样。它要求""LineTrailColor=""和""LineTrailColorDecrement=""都存在且值有效。"},
{"LineTrailColor", "指定轨迹线的RGB颜色（如果存在的话）。"},
{"LineTrailColorDecrement", "指定轨迹线有多长（如果有的话）。数值越大代表轨迹线越短。"},
{"Foundation", "决定建筑有多大，部署该建筑需要多少格。它采用的格式为""宽 x 长""，其中宽为该建筑在东南或者西北方向上所占的格子数，长为该建筑在西南或者东北方向上所占的格子数。"},
{"Height", "指定该建筑有多高（单位为格）。它用于决定当选中该建筑时，出现的白色虚线框的高度，还有基洛夫空艇、火箭飞行兵或其他任何飞行单位打算飞过该建筑时需要升高的高度。"},
{"Buildup", "决定建造该建筑的时候使用哪个SHP图像作为建造动画。卖建筑的时候，动画倒退播放。这个动画应该少于100帧左右，并且每个可建造的建筑都必须要有""Buildup=""，否则就不能被卖掉。如果你没有建造动画，随便找一个小短动画作为临时建造动画。"},
{"DemandLoadBuildup", "提前载入建造动画"},
{"FreeBuildup", "可被设定为""true""或者""false""。这个标签的功能未知。不过，一般被设定为true。"},
{"Recoilless", "如果被设定为yes，那么它将告知游戏该建筑不使用后坐力武器或者炮塔，从而应该调整。"},
{"ToOverlay", "指定该建筑将会转化为哪个覆盖物。一般用于允许玩家建造城墙和公路和宝箱"},
{"DamageLevels", "指定一个城墙的SHP文件有多少损坏的程度。每一种损坏的程度都是一整套城墙的图像，而破损增加。（就是说每坏得更厉害一次，都需要一整套城墙的图像。）"},
{"PowerUp1Anim", "指定当该建筑加盖1次时加到建筑上的动画。"},
{"PowerUp2Anim", "指定当该建筑加盖2次时加到建筑上的动画。"},
{"PowerUp3Anim", "指定当该建筑加盖3次时加到建筑上的动画。"},
{"PowerUp1AnimDamaged", "指定当该建筑加盖1次时生命低于50%加到建筑上的动画。"},
{"PowerUp2AnimDamaged", "指定当该建筑加盖2次时生命低于50%加到建筑上的动画。"},
{"PowerUp3AnimDamaged", "指定当该建筑加盖3次时生命低于50%加到建筑上的动画。"},
{"PowerUp1LocX", "指定绘制建筑的升级模块1距离绘制建筑的位置的X轴像素偏移量。建筑的绘制位置是在该建筑的SHP图像的左上方。"},
{"PowerUp2LocX", "指定绘制建筑的升级模块2距离绘制建筑的位置的X轴像素偏移量。建筑的绘制位置是在该建筑的SHP图像的左上方。"},
{"PowerUp3LocX", "指定绘制建筑的升级模块3距离绘制建筑的位置的X轴像素偏移量。建筑的绘制位置是在该建筑的SHP图像的左上方。"},
{"PowerUp1LocY", "指定绘制建筑的升级模块1距离绘制建筑的位置的Y轴像素偏移量。建筑的绘制位置是在该建筑的SHP图像的左上方。"},
{"PowerUp2LocY", "指定绘制建筑的升级模块2距离绘制建筑的位置的Y轴像素偏移量。建筑的绘制位置是在该建筑的SHP图像的左上方。"},
{"PowerUp3LocY", "指定绘制建筑的升级模块3距离绘制建筑的位置的Y轴像素偏移量。建筑的绘制位置是在该建筑的SHP图像的左上方。"},
{"PowerUp1YSort", "为升级模块1如何绘制创建顺序。如果和其他升级模块相交迭的话，数值最低的升级模块将会在其他模块和动画后面绘制。这些标签使ActiveAnimYSort关联，确定谁遮挡谁"},
{"PowerUp2YSort", "为升级模块2如何绘制创建顺序。如果和其他升级模块相交迭的话，数值最低的升级模块将会在其他模块和动画后面绘制。这些标签使ActiveAnimYSort关联，确定谁遮挡谁"},
{"PowerUp3YSort", "为升级模块3如何绘制创建顺序。如果和其他升级模块相交迭的话，数值最低的升级模块将会在其他模块和动画后面绘制。这些标签使ActiveAnimYSort关联，确定谁遮挡谁"},
{"ActiveAnim", "指定当该建筑建造起来之后正常运行或者没有严重损坏（就是绿血的状态……）的时候播放的动画。"},
{"ActiveAnimTwo", "指定当该建筑建造起来之后正常运行或者没有严重损坏（就是绿血的状态……）的时候播放的动画。"},
{"ActiveAnimThree", "指定当该建筑建造起来之后正常运行或者没有严重损坏（就是绿血的状态……）的时候播放的动画。"},
{"ActiveAnimDamaged", "指定该建筑以少于50%的HP运行的时候播放的动画。"},
{"ActiveAnimTwoDamaged", "指定该建筑以少于50%的HP运行的时候播放的动画。"},
{"ActiveAnimThreeDamaged", "指定该建筑以少于50%的HP运行的时候播放的动画。"},
{"ActiveAnimX", "指定距离该建筑绘制坐标的X坐标。默认值为0。红警2中无用，因为大多数建筑的动态动画和建筑一样大。"},
{"ActiveAnimTwoX", "指定距离该建筑绘制坐标的X坐标。默认值为0。红警2中无用，因为大多数建筑的动态动画和建筑一样大。"},
{"ActiveAnimThreeX", "指定距离该建筑绘制坐标的X坐标。默认值为0。红警2中无用，因为大多数建筑的动态动画和建筑一样大。"},
{"ActiveAnimY", "指定距离该建筑绘制坐标的Y坐标。默认值为0。红警2中无用，因为大多数建筑的动态动画和建筑一样大。"},
{"ActiveAnimTwoY", "指定距离该建筑绘制坐标的Y坐标。默认值为0。红警2中无用，因为大多数建筑的动态动画和建筑一样大。"},
{"ActiveAnimThreeY", "指定距离该建筑绘制坐标的Y坐标。默认值为0。红警2中无用，因为大多数建筑的动态动画和建筑一样大。"},
{"ActiveAnimYSort", "为如何绘制动态动画1创建顺序。YSort数值低的动态动画将会在其他ActiveAnim或PowerUp后面绘制。就像""PowerUp1YSort=""一样。"},
{"ActiveAnimTwoYSort", "为如何绘制动态动画2创建顺序。YSort数值低的动态动画将会在其他ActiveAnim或PowerUp后面绘制。就像""PowerUp2YSort=""一样。"},
{"ActiveAnimThreeYSort", "为如何绘制动态动画3创建顺序。YSort数值低的动态动画将会在其他ActiveAnim或PowerUp后面绘制。就像""PowerUp3YSort=""一样。"},
{"ActiveAnimZAdjust", "调整动画在层次上的数值。默认为0。ActiveAnim的z值决定了动态动画到底处于哪一个层次上。最低的z值意味着""处于所有图像的后面""，同样，最高的z值意味着""处于所有图像的前方""。"},
{"ActiveAnimTwoZAdjust", "调整动画在层次上的数值。默认为0。ActiveAnim的z值决定了动态动画到底处于哪一个层次上。最低的z值意味着""处于所有图像的后面""，同样，最高的z值意味着""处于所有图像的前方""。"},
{"ActiveAnimThreeZAdjust", "调整动画在层次上的数值。默认为0。ActiveAnim的z值决定了动态动画到底处于哪一个层次上。最低的z值意味着""处于所有图像的后面""，同样，最高的z值意味着""处于所有图像的前方""。"},
{"ActiveAnimPowered", "如果被设置为yes，那么ActiveAnim只有在玩家拥有足够的电力的时候才被播放（这就是为什么一旦电力不够，电厂就失去了动画效果的缘故……）。否则，在电力切断之前动态动画会在播放完全部的帧之后停止播放并冻结在最后一帧。"},
{"ActiveAnimTwoPowered", "如果被设置为yes，那么ActiveAnim只有在玩家拥有足够的电力的时候才被播放（这就是为什么一旦电力不够，电厂就失去了动画效果的缘故……）。否则，在电力切断之前动态动画会在播放完全部的帧之后停止播放并冻结在最后一帧。"},
{"ActiveAnimThreePowered", "如果被设置为yes，那么ActiveAnim只有在玩家拥有足够的电力的时候才被播放（这就是为什么一旦电力不够，电厂就失去了动画效果的缘故……）。否则，在电力切断之前动态动画会在播放完全部的帧之后停止播放并冻结在最后一帧。"},
{"SpecialAnim", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimTwo", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimThree", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimDamaged", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimTwoDamaged", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimThreeDamaged", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimZAdjust", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimTwoZAdjust", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimThreeZAdjust", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimX", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimTwoX", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimThreeX", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimY", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimTwoY", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimThreeY", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimYSort", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimTwoYSort", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"SpecialAnimThreeYSort", "这些标签就像ActiveAnim一样，只不过这些是用于当该建筑执行特殊功能时。因此并不是一直有效，只有需要的时候才有效。"},
{"ProductionAnim", "这些标签也像ActiveAnim一样，只不过用于建造厂，当玩家拥有了一个这样的建筑并建造的时候有效。"},
{"ProductionAnimDamaged", "这些标签也像ActiveAnim一样，只不过用于建造厂，当玩家拥有了一个这样的建筑并建造的时候有效。"},
{"ProductionAnimZAdjust", "这些标签也像ActiveAnim一样，只不过用于建造厂，当玩家拥有了一个这样的建筑并建造的时候有效。"},
{"ProductionAnimYSort", "这些标签也像ActiveAnim一样，只不过用于建造厂，当玩家拥有了一个这样的建筑并建造的时候有效。"},
{"ProductionAnimX", "这些标签也像ActiveAnim一样，只不过用于建造厂，当玩家拥有了一个这样的建筑并建造的时候有效。"},
{"ProductionAnimY", "这些标签也像ActiveAnim一样，只不过用于建造厂，当玩家拥有了一个这样的建筑并建造的时候有效。"},
{"SuperAnim", "这些标签也像ActiveAnim一样，只不过这些用于属于该建筑的超级武器激活的时候有效。"},
{"SuperAnimDamaged", "这些标签也像ActiveAnim一样，只不过这些用于属于该建筑的超级武器激活的时候有效。"},
{"SuperAnimZAdjust", "这些标签也像ActiveAnim一样，只不过这些用于属于该建筑的超级武器激活的时候有效。"},
{"SuperAnimYSort", "这些标签也像ActiveAnim一样，只不过这些用于属于该建筑的超级武器激活的时候有效。"},
{"SuperAnimX", "这些标签也像ActiveAnim一样，只不过这些用于属于该建筑的超级武器激活的时候有效。"},
{"SuperAnimY", "这些标签也像ActiveAnim一样，只不过这些用于属于该建筑的超级武器激活的时候有效。"},
{"PrimaryFirePixelOffset", "规定武器开火的位置。和PrimaryFireFLH不同的是它的单位是""像素""而不是""lepton""。通常用于无炮塔的建筑。第一个参数为距离图像中心的x坐标，第二个参数则是y坐标。默认值为0,0，且不管武器从哪个方向开火，它都只从同一个位置开火。这一点不像PrimaryFireFLH一样考虑开火位置的移动。"},
{"SecondaryFirePixelOffset", "规定武器开火的位置。和SecondaryFireFLH不同的是它的单位是""像素""而不是""lepton""。通常用于无炮塔的建筑。第一个参数为距离图像中心的x坐标，第二个参数则是y坐标。默认值为0,0，且不管武器从哪个方向开火，它都只从同一个位置开火。这一点不像PrimaryFireFLH一样考虑开火位置的移动。"},
{"PrimaryFireDualOffset", "当设置为true的时候，表示建筑同时使用PrimaryFirePixelOffset和PrimaryFireFLH。它允许建筑使用PrimaryFirePixelOffset来确定0,0,0（从PrimarFireFLH）的位置，而不是正中心。当要求某个不对称的建筑看起来像有个炮塔（其实没有）的时候使用这个标签会很有效。"},
{"QueueingCell", "指定当一个矿车在朝矿厂里面倒矿，另一个矿车在旁边等待倒矿的时候，那个等着的矿车所在的格子的x,y坐标（就按照这种顺序）。这个参数按照如下确定：从建筑的西角开始数，向东北方向x坐标增加，向东南方向y坐标增加。"},
{"BibShape", "指定用作""Bib""的图像。Bib是指建筑的某个部分，单位可以越过这个部分。此时游戏将单位绘制到Bib的上面而不是下面。"},
{"DockingOffset0", "表示入坞距离建筑的Bib中心0（如果有Bib的话）或者建筑本身的偏移量x,y,z坐标（朝向东北意味着x增加，朝向东南意味着y增加，朝向上意味着z增加）。单位是lepton。"},
{"DockingOffset1", "表示入坞距离建筑的Bib中心1（如果有Bib的话）或者建筑本身的偏移量x,y,z坐标（朝向东北意味着x增加，朝向东南意味着y增加，朝向上意味着z增加）。单位是lepton。"},
{"DockingOffset2", "表示入坞距离建筑的Bib中心2（如果有Bib的话）或者建筑本身的偏移量x,y,z坐标（朝向东北意味着x增加，朝向东南意味着y增加，朝向上意味着z增加）。单位是lepton。"},
{"DockingOffset3", "表示入坞距离建筑的Bib中心3（如果有Bib的话）或者建筑本身的偏移量x,y,z坐标（朝向东北意味着x增加，朝向东南意味着y增加，朝向上意味着z增加）。单位是lepton。"},
{"DamageFireOffset0", "指定当建筑被破坏到HP少于50%的时候播放的着火的动画0。参数的单位为像素，格式为x,y，默认在SHP的中心播放。"},
{"DamageFireOffset1", "指定当建筑被破坏到HP少于50%的时候播放的着火的动画1。参数的单位为像素，格式为x,y，默认在SHP的中心播放。"},
{"DamageFireOffset2", "指定当建筑被破坏到HP少于50%的时候播放的着火的动画2。参数的单位为像素，格式为x,y，默认在SHP的中心播放。"},
{"DamageFireOffset3", "指定当建筑被破坏到HP少于50%的时候播放的着火的动画3。参数的单位为像素，格式为x,y，默认在SHP的中心播放。"},
{"IsAnimDelayedFire", "如果被设置为yes，那么当建筑被指定攻击一个在射程范围内的目标的时候，开火前会产生硬直。下面一个标签用于控制该硬直时间。"},
{"DelayedFireDelay", "指定开火硬直时间的帧数（游戏在中速的时候大约15fps）。它用于同步建筑开火的动画。"},
{"TerrainPalette", "如果被设置为yes，则建筑会使用地形调色盘isotem.pal、isourb.pal和isosno.pal。尤里的复仇中还包括isodes.pal和isolun.pal。只在泰伯利亚之日中使用"},
{"CanHideThings", "可被设置为true或者false。指定是否游戏会自动指明被认为是被该建筑挡住了的动画的格子，并同时显示""隐藏物品""动画。（就是说如果游戏选中了""显示隐藏物品""的选项，且该建筑的这个标签被设为true，则被该建筑挡住的对象会显示出一个闪烁的光标表示这里有东西……）"},
{"AddOccupy1", "指定某个单位被设定为隐藏时，在顶层会显示出表示隐藏的动画所附加的格子。它的格式是从建筑偏移位置开始的x和y的偏移量。"},
{"AddOccupy2", "指定某个单位被设定为隐藏时，在顶层会显示出表示隐藏的动画所附加的格子。它的格式是从建筑偏移位置开始的x和y的偏移量。"},
{"AddOccupy3", "指定某个单位被设定为隐藏时，在顶层会显示出表示隐藏的动画所附加的格子。它的格式是从建筑偏移位置开始的x和y的偏移量。"},
{"AddOccupy4", "指定某个单位被设定为隐藏时，在顶层会显示出表示隐藏的动画所附加的格子。它的格式是从建筑偏移位置开始的x和y的偏移量。"},
{"RemoveOccupy1", "不考虑CanHideThings=所指定的格子。单位能够占据这么多格子，而不会显示表示隐藏的动画。它的格式是从建筑偏移位置开始的x和y的偏移量。"},
{"RemoveOccupy2", "不考虑CanHideThings=所指定的格子。单位能够占据这么多格子，而不会显示表示隐藏的动画。它的格式是从建筑偏移位置开始的x和y的偏移量。"},
{"RemoveOccupy3", "不考虑CanHideThings=所指定的格子。单位能够占据这么多格子，而不会显示表示隐藏的动画。它的格式是从建筑偏移位置开始的x和y的偏移量。"},
{"RemoveOccupy4", "不考虑CanHideThings=所指定的格子。单位能够占据这么多格子，而不会显示表示隐藏的动画。它的格式是从建筑偏移位置开始的x和y的偏移量。"},
{"CanBeHidden", "指定该建筑是否能够被位于它前方的更高的建筑挡住。可以被设置为true或者false。"},
{"OccupyHeight", "指定OccupyCell（由AddOccupy和CanHideThings=指定）有多高。漂浮在OccupyCell上且低于OccupyHeight的火箭飞行兵会被认为是被挡住，而飞到其上方，则不被认为挡住。"},
{"DoubleThick", "如果被设置为true，则该建筑或者动画被超时空兵种攻击的时候会出现额外的半透明效果。用于当建筑有两个或者更多的层且其中一个半透明的层不够用的情况。 " + vbCrLf +
"用作抛射体的动画AnimLow,AnimHigh,AnimRate  这三条用于动画抛射体，抛射体飞行中会播放动画而非停留在第一帧。low和high等于是loopstart和loopend"},
{"Rotates", "如果被设置为yes，它将告知游戏这个抛射体使用一个具有64帧的SHP，且这些帧显示出一个旋转了360°的抛射体。这使得游戏能够正确显示出导弹按照它的方向移动的帧。"},
{"AnimPalette", "如果被设置为yes，游戏绘制SHP图像时将会使用anim.pal调色盘，而不是unittem.pal、unitsno.pal或者uniturb.pal调色盘。"},
{"Flat", "如果被设置为yes，游戏在绘制地表层的时候将会绘制该抛射体，然后在其上面绘制其它部分。这个标签将会让抛射体在其他单位下方移动。"},
{"Ready", "用于当步兵单位站在那里等待的时候。"},
{"Guard", "用于当步兵单位被置于防御模式中。在红警2中似乎使用的不多。"},
{"Tread", "指定当步兵单位在水中游泳，并不断打水保持自己浮在水面上的帧序列。（谭雅？）"},
{"Prone", "指定步兵单位卧倒（企图减少伤害）的所有帧序列。"},
{"Walk", "指定当步兵行走的时候的帧序列。"},
{"Swim", "指定当步兵在水中游泳的帧序列。"},
{"WetAttack", "指定当步兵单位在水中向敌方单位开火的帧序列。"},
{"Down", "指定当步兵单位遭到攻击卧倒的帧序列。"},
{"Crawl", "指定当步兵单位爬行的帧序列。当步兵在移动的时候遭到攻击会出现这种动作。"},
{"Up", "指定当危险过后步兵单位站起来的帧序列。"},
{"Idle1", "指定当步兵单位站着闲得没事的帧序列1。这会使步兵单位不至于看起来像一尊雕像一样。"},
{"Idle2", "指定当步兵单位站着闲得没事的帧序列2。这会使步兵单位不至于看起来像一尊雕像一样。"},
{"WetIdle1", "指定当步兵单位站着闲得没事的帧序列1。这会使步兵单位不至于看起来像一尊雕像一样。 这里的标签指的是水中。"},
{"WetIdle2", "指定当步兵单位站着闲得没事的帧序列2。这会使步兵单位不至于看起来像一尊雕像一样。 这里的标签指的是水中。"},
{"Die1", "指定当步兵单位被某种拥有InfDeath=1弹头的武器杀死的帧序列。"},
{"Die2", "指定当步兵单位被某种拥有InfDeath=2弹头的武器杀死的帧序列。可能会从Die2=和Die3=中随机选择一种。"},
{"Die3", "指定当步兵单位被某种拥有InfDeath=1弹头的武器杀死的帧序列。可能会从Die3=和Die2=中随机选择一种。"},
{"Die4", "指定当步兵单位被某种拥有InfDeath=3弹头的武器杀死的帧序列。"},
{"Die5", "指定当步兵单位被某种拥有InfDeath=4弹头的武器杀死的帧序列。"},
{"WetDie1", "指定当步兵单位在水中被杀死的帧序列。可能会从WetDie1=和WetDie2=中随机选择一种。"},
{"WetDie2", "指定当步兵单位在水中被杀死的帧序列。可能会从WetDie2=和WetDie1=中随机选择一种。"},
{"Deploy", "指定当步兵单位被命令""部署""从而激活某种功能（就像美国大兵会在身边摆放沙袋并架起机关枪）的帧序列。"},
{"Deployed", "指定当步兵单位被部署且目前闲的没事的帧序列。"},
{"Undeploy", "指定当步兵被命令""取消部署""的帧序列。"},
{"Cheer", "指定步兵单位欢呼的帧序列。"},
{"Paradrop", "指定当步兵单位被空投到战场上的帧。该帧不要有影子。"},
{"Scorch", "如果被设置为yes，动画会在战场上留下烧焦的痕迹（燃烧""污染""），纯粹就是图像效果。"},
{"Crater", "如果被设置为yes，动画会在战场上留下弹坑的痕迹，当然也是图像效果。"},
{"PsiWarning", "如果被设置为yes，动画会在核弹发射的时候为拥有心灵感应器的玩家播放。"},
{"Sticky", "如果被设置为yes，动画会附着在目标上。但是这条语句是无效的。"},
{"Translucent", "如果被设置为yes，它将告诉游戏该动画半透明。导致卡的元凶之一"},
{"Translucency", "指定动画的半透明效果为多少。可取值25、50或75意味着25%、50%或75%透明（值越大越透明）。"},
{"Damage", "一帧造成一次伤害，范围和动画弹头一样。原版inviso弹头为super，其它为fire2，不能修改"},
{"Report", "指定当播放动画的时候播放的声音。声音应当和soundmd.ini文件中的片断头相匹配。"},
{"Next", "指定当前动画已经停止播放之后播放的动画。这也包括当它已经循环播放数次之后的情形。"},
{"DetailLevel", "推测是指定图像中显示细节的数量。此时观察无效。"},
{"UseNormalLight", "如果被设置为yes，那么动画将一直以100%的亮度播放（即使此时屏幕由于闪电风暴超级武器变暗）。"},
{"YSortAdjust", "指定动画的YSort值，该值用于使位于某个单位背后（就像超时空部队的空间扭曲图像），或者在单位前方（就像超时空传送启动动画）的动画可以显示出来。"},
{"Tiled", "是否把动画摞成柱状，像ts的离子风暴那样。"},
{"TranslucencyDetailLevel", "由不透明渐渐变透明。"},
{"ZSortAdjust", "指定动画的ZSort值，该值用于使某个位于建筑背后或者前方的动画可以显示出来。"},
{"AltPalette", "如果被设置为yes，那么动画将会使用unittem.pal，unitsno.pal和uniturb.pal作为调色盘进行描绘，而不是使用anim.pal作为调色盘。"},
{"Rate", "决定动画的播放速度。数值越大代表播放速度越快。这个数值以900帧为基数。Rate=300代表游戏将判定动画每帧之间插入900/300帧时间。"},
{"Layer", "决定动画在哪个层上播放。""Top""意味着在所有之上（包括力场护盾——试图用闪电风暴击打力场护盾）。""Ground""意味着战场。"},
{"Start", "指定动画的起始帧。默认从0开始。"},
{"LoopStart", "指定动画开始循环的帧序号。这和Start=不同。游戏会从Start=那一帧开始播放，一直到LoopEnd=那一帧停止，然后从LoopStart=那一帧继续播放。"},
{"LoopEnd", "指定动画的结束帧。如果没有到LoopCount=所指定的循环次数，它将会跳到LoopStart=那一帧继续播放。"},
{"LoopCount", "指定动画播放的次数。第一次播放被认为是循环次数为0（就是说第一次播放相当于循环了0次，第二次播放相当于循环了一次）。当动画播放到了LoopEnd=那一帧时，循环次数加1，同时检测LoopCount=看是否还需要循环。如果LoopCount=被设置为-1，动画将永远不会停止。（正数再怎么加1也不可能加成-1……）"},
{"Elasticity", "碎片弹性，01之间，越大越强。必须Bouncer= yes才有效"},
{"MaxXYVel", "碎片在平面上的速度，不得小于1"},
{"MaxZVel", "碎片的竖直速度，正数为向上飞"},
{"ExpireAnim", "碎片爆炸动画。可以是另一个碎片的名字"},
{"DamageRadius", "伤害范围，单位lepton，似乎无效，用弹头的cellspread计数"},
{"Warhead", "碎片弹头"},
{"IsMeteor", "此动画将会从天而降"},
{"Spawns", "撞击产生子碎片类型"},
{"SpawnCount", "子碎片数目"},
{"Bouncer", "yes或no，与Elasticity配合使用"},
{"RandomRate", "填两个数字，碎片shp的播放速度从此区间产生"},
{"TiberiumSpawnType", "产生覆盖物的种类，如GEM01"},
{"TiberiumSpawnRadius", "产矿范围， 无效， 只能一格一层"},
{"Image", "引用其它的图像作为此动画的贴图"},
{"MuzzleFlash0", "枪口0在楼里闪光的位置"},
{"MuzzleFlash1", "枪口1在楼里闪光的位置"},
{"MuzzleFlash2", "枪口2在楼里闪光的位置"},
{"MuzzleFlash3", "枪口3在楼里闪光的位置"},
{"MuzzleFlash4", "枪口4在楼里闪光的位置"},
{"MuzzleFlash5", "枪口5在楼里闪光的位置"},
{"MuzzleFlash6", "枪口6在楼里闪光的位置"},
{"MuzzleFlash7", "枪口7在楼里闪光的位置"},
{"MuzzleFlash8", "枪口8在楼里闪光的位置"},
{"MuzzleFlash9", "枪口9在楼里闪光的位置"}
}

    Private Shared ArtTypes As New Dictionary(Of String, String) From {{"Cameo", "String"},
{"AltCameo", "String"},
{"Sequence", "String"},
{"Crawls", "Boolean"},
{"Remapable", "Boolean"},
{"FireUp", "Integer"},
{"PrimaryFireFLH", "IEnumerable(Of Integer)"},
{"Image", "String"},
{"SecondaryFireFLH", "IEnumerable(Of Integer)"},
{"SecondaryFire", "Integer"},
{"Ready", "IEnumerable(Of Integer)"},
{"Guard", "IEnumerable(Of Integer)"},
{"Walk", "IEnumerable(Of Integer)"},
{"Idle1", "IEnumerable(Of Integer)"},
{"Idle2", "IEnumerable(Of Integer)"},
{"Crawl", "IEnumerable(Of Integer)"},
{"Prone", "IEnumerable(Of Integer)"},
{"Die1", "IEnumerable(Of Integer)"},
{"Die2", "IEnumerable(Of Integer)"},
{"FireProne", "IEnumerable(Of Integer)"},
{"Down", "IEnumerable(Of Integer)"},
{"Up", "IEnumerable(Of Integer)"},
{"Paradrop", "IEnumerable(Of Integer)"},
{"Cheer", "IEnumerable(Of Integer)"},
{"Tread", "IEnumerable(Of Integer)"},
{"Swim", "IEnumerable(Of Integer)"},
{"WetAttack", "IEnumerable(Of Integer)"},
{"WetIdle1", "IEnumerable(Of Integer)"},
{"WetIdle2", "IEnumerable(Of Integer)"},
{"WetDie1", "IEnumerable(Of Integer)"},
{"WetDie2", "IEnumerable(Of Integer)"},
{"Die3", "IEnumerable(Of Integer)"},
{"Die4", "IEnumerable(Of Integer)"},
{"Die5", "IEnumerable(Of Integer)"},
{"Panic", "IEnumerable(Of Integer)"},
{"Deploy", "IEnumerable(Of Integer)"},
{"Deployed", "IEnumerable(Of Integer)"},
{"DeployedFire", "IEnumerable(Of Integer)"},
{"DeployedIdle", "IEnumerable(Of Integer)"},
{"Undeploy", "IEnumerable(Of Integer)"},
{"Idle1Sounds", "String"},
{"Voxel", "Boolean"},
{"WalkFrames", "Integer"},
{"FiringFrames", "Integer"},
{"PBarrelLength", "Integer"},
{"TurretOffset", "Integer"},
{"AlternateFLH0", "IEnumerable(Of Integer)"},
{"AlternateFLH1", "IEnumerable(Of Integer)"},
{"AlternateFLH2", "IEnumerable(Of Integer)"},
{"AlternateFLH3", "IEnumerable(Of Integer)"},
{"AlternateFLH4", "IEnumerable(Of Integer)"},
{"DisableShadowCache", "Boolean"},
{"SecondSpawnOffset", "IEnumerable(Of Integer)"},
{"TrailerAnim", "String"},
{"SpawnDelay", "Integer"},
{"Trailer", "String"},
{"TrailerSeperation", "Integer"},
{"CanBeHidden", "Boolean"},
{"Weapon1FLH", "IEnumerable(Of Integer)"},
{"Weapon2FLH", "IEnumerable(Of Integer)"},
{"Weapon3FLH", "IEnumerable(Of Integer)"},
{"Weapon4FLH", "IEnumerable(Of Integer)"},
{"Weapon5FLH", "IEnumerable(Of Integer)"},
{"Weapon6FLH", "IEnumerable(Of Integer)"},
{"Weapon7FLH", "IEnumerable(Of Integer)"},
{"Weapon8FLH", "IEnumerable(Of Integer)"},
{"Weapon9FLH", "IEnumerable(Of Integer)"},
{"Weapon10FLH", "IEnumerable(Of Integer)"},
{"Weapon11FLH", "IEnumerable(Of Integer)"},
{"Weapon12FLH", "IEnumerable(Of Integer)"},
{"Weapon13FLH", "IEnumerable(Of Integer)"},
{"Weapon14FLH", "IEnumerable(Of Integer)"},
{"Weapon15FLH", "IEnumerable(Of Integer)"},
{"Weapon16FLH", "IEnumerable(Of Integer)"},
{"Weapon17FLH", "IEnumerable(Of Integer)"},
{"EliteWeapon1FLH", "IEnumerable(Of Integer)"},
{"EliteWeapon2FLH", "IEnumerable(Of Integer)"},
{"EliteWeapon3FLH", "IEnumerable(Of Integer)"},
{"EliteWeapon4FLH", "IEnumerable(Of Integer)"},
{"ElitePrimaryFireFLH", "IEnumerable(Of Integer)"},
{"EliteSecondaryFireFLH", "IEnumerable(Of Integer)"},
{"EliteWeapon5FLH", "IEnumerable(Of Integer)"},
{"EliteWeapon6FLH", "IEnumerable(Of Integer)"},
{"UseBuffer", "Boolean"},
{"DisableVoxelCache", "Boolean"},
{"ShadowIndex", "Integer"},
{"Normalized", "Boolean"},
{"Height", "Integer"},
{"Foundation", "String"},
{"Buildup", "String"},
{"DemandLoadBuildup", "Boolean"},
{"FreeBuildup", "Boolean"},
{"NewTheater", "Boolean"},
{"ActiveAnim", "String"},
{"ActiveAnimDamaged", "String"},
{"ActiveAnimZAdjust", "Integer"},
{"CanHideThings", "Boolean"},
{"OccupyHeight", "Integer"},
{"DamageFireOffset0", "IEnumerable(Of Integer)"},
{"DamageFireOffset1", "IEnumerable(Of Integer)"},
{"DamageFireOffset2", "IEnumerable(Of Integer)"},
{"AddOccupy1", "IEnumerable(Of Integer)"},
{"AddOccupy2", "IEnumerable(Of Integer)"},
{"AddOccupy3", "IEnumerable(Of Integer)"},
{"AddOccupy4", "IEnumerable(Of Integer)"},
{"LoopStart", "Integer"},
{"LoopEnd", "Integer"},
{"LoopCount", "Integer"},
{"Rate", "Integer"},
{"Layer", "String"},
{"AnimActive", "IEnumerable(Of Integer)"},
{"ZShapePointMove", "IEnumerable(Of Integer)"},
{"DeployingAnim", "String"},
{"ActiveAnimYSort", "Integer"},
{"UnderDoorAnim", "String"},
{"BibShape", "String"},
{"ActiveAnimTwo", "String"},
{"ActiveAnimTwoDamaged", "String"},
{"ActiveAnimTwoZAdjust", "Integer"},
{"RoofDeployingAnim", "String"},
{"UnderRoofDoorAnim", "String"},
{"RemoveOccupy1", "IEnumerable(Of Integer)"},
{"RemoveOccupy2", "IEnumerable(Of Integer)"},
{"RemoveOccupy3", "IEnumerable(Of Integer)"},
{"RemoveOccupy4", "IEnumerable(Of Integer)"},
{"RemoveOccupy5", "IEnumerable(Of Integer)"},
{"RemoveOccupy6", "IEnumerable(Of Integer)"},
{"RemoveOccupy7", "IEnumerable(Of Integer)"},
{"RemoveOccupy8", "IEnumerable(Of Integer)"},
{"Start", "Integer"},
{"DeployingAnimDamaged", "String"},
{"UnderDoorAnimDamaged", "String"},
{"UnderDoorAnimZAdjust", "Integer"},
{"RoofDeployingAnimDamaged", "String"},
{"UnderRoofDoorAnimDamaged", "String"},
{"RemoveOccupy", "IEnumerable(Of Integer)"},
{"End", "Integer"},
{"ProductionAnim", "String"},
{"ProductionAnimDamaged", "String"},
{"ProductionAnimZAdjust", "Integer"},
{"ProductionAnimYSort", "Integer"},
{"IdleAnim", "String"},
{"IdleAnimDamaged", "String"},
{"IdleAnimZAdjust", "Integer"},
{"IdleAnimYSort", "Integer"},
{"Shadow", "Boolean"},
{"QueueingCell", "IEnumerable(Of Integer)"},
{"ActiveAnimThree", "String"},
{"ActiveAnimThreeZAdjust", "Integer"},
{"ActiveAnimThreeDamaged", "String"},
{"ActiveAnimFour", "String"},
{"ActiveAnimFourZAdjust", "Integer"},
{"ActiveAnimFourDamaged", "String"},
{"SpecialAnim", "String"},
{"SpecialAnimZAdjust", "Integer"},
{"ActiveAnimTwoYSort", "Integer"},
{"ActiveAnimThreeYSort", "Integer"},
{"ActiveAnimFourYSort", "Integer"},
{"SpecialAnimYSort", "Integer"},
{"DamageFireOffset3", "IEnumerable(Of Integer)"},
{"SiloDamage", "Boolean"},
{"SpecialAnimDamaged", "String"},
{"Flat", "Boolean"},
{"ActiveAnimY", "Integer"},
{"DockingOffset0", "IEnumerable(Of Integer)"},
{"DockingOffset1", "IEnumerable(Of Integer)"},
{"DockingOffset2", "IEnumerable(Of Integer)"},
{"DockingOffset3", "IEnumerable(Of Integer)"},
{"SuperAnim", "String"},
{"SuperAnimDamaged", "String"},
{"SuperAnimZAdjust", "Integer"},
{"SuperAnimTwo", "String"},
{"SuperAnimTwoDamaged", "String"},
{"SuperAnimTwoZAdjust", "Integer"},
{"SuperAnimThree", "String"},
{"SuperAnimThreeDamaged", "String"},
{"SuperAnimThreeZAdjust", "Integer"},
{"SuperAnimFour", "String"},
{"SuperAnimFourDamaged", "String"},
{"SuperAnimFourZAdjust", "Integer"},
{"SuperAnimPowered", "Boolean"},
{"SuperAnimTwoPowered", "Boolean"},
{"SuperAnimThreePowered", "Boolean"},
{"SuperAnimFourPowered", "Boolean"},
{"SuperAnimThreePoweredEffect", "Boolean"},
{"SuperLowPower", "String"},
{"SuperLowPowerDamaged", "String"},
{"SuperLowPowerPowered", "Boolean"},
{"StartSound", "String"},
{"SuperAnimYSort", "Integer"},
{"SuperAnimTwoYSort", "Integer"},
{"SuperAnimThreeYSort", "Integer"},
{"SuperAnimFourYSort", "Integer"},
{"IdleAnimTwo", "String"},
{"IdleAnimTwoDamaged", "String"},
{"IdleAnimTwoZAdjust", "Integer"},
{"IdleAnimPowered", "Boolean"},
{"ActiveAnimThreePowered", "Boolean"},
{"SpecialAnimTwo", "String"},
{"SpecialAnimTwoDamaged", "String"},
{"SpecialAnimTwoZAdjust", "Integer"},
{"SpecialAnimTwoYSort", "Integer"},
{"SpecialAnimThree", "String"},
{"SpecialAnimThreeDamaged", "String"},
{"SpecialAnimThreeZAdjust", "Integer"},
{"SpecialAnimThreeYSort", "Integer"},
{"AddOccupy5", "IEnumerable(Of Integer)"},
{"AddOccupy6", "IEnumerable(Of Integer)"},
{"ActiveAnimPowered", "Boolean"},
{"ActiveAnimTwoPowered", "Boolean"},
{"ActiveAnimTwoPoweredLight", "Boolean"},
{"ActiveAnimThreePoweredLight", "Boolean"},
{"PowerUp1LocXX", "Integer"},
{"PowerUp1LocYY", "Integer"},
{"PowerUp1LocZZ", "Integer"},
{"PowerUp1YSort", "Integer"},
{"PowerUp2LocXX", "Integer"},
{"PowerUp2LocYY", "Integer"},
{"PowerUp2LocZZ", "Integer"},
{"PowerUp2YSort", "Integer"},
{"ActiveAnimPoweredSpecial", "Boolean"},
{"LowPower", "String"},
{"LowPowerDamaged", "String"},
{"LowPowerPowered", "Boolean"},
{"DemandLoad", "Boolean"},
{"TerrainPalette", "Boolean"},
{"ExtraDamageStage", "Boolean"},
{"ExtraLight", "Integer"},
{"TurretNotExportedOnGround", "Boolean"},
{"DoubleThick", "Boolean"},
{"ToOverlay", "String"},
{"DamageLevels", "Integer"},
{"MuzzleFlash0", "IEnumerable(Of Integer)"},
{"MuzzleFlash1", "IEnumerable(Of Integer)"},
{"MuzzleFlash2", "IEnumerable(Of Integer)"},
{"MuzzleFlash3", "IEnumerable(Of Integer)"},
{"MuzzleFlash4", "IEnumerable(Of Integer)"},
{"MuzzleFlash5", "IEnumerable(Of Integer)"},
{"MuzzleFlash6", "IEnumerable(Of Integer)"},
{"MuzzleFlash7", "IEnumerable(Of Integer)"},
{"MuzzleFlash8", "IEnumerable(Of Integer)"},
{"MuzzleFlash9", "IEnumerable(Of Integer)"},
{"Theater", "Boolean"},
{"SpecialZOverlay", "String"},
{"GateStages", "Integer"},
{"DetailLevel", "Integer"},
{"ShouldUseCellDrawer", "Boolean"},
{"Report", "String"},
{"YDrawOffset", "Integer"},
{"ChargeAnim", "Boolean"},
{"PrimaryFirePixelOffset", "IEnumerable(Of Integer)"},
{"ActiveAnimPoweredLight", "Boolean"},
{"SpecialAnimPowered", "Boolean"},
{"SpecialAnimPoweredLight", "Boolean"},
{"IsAnimDelayedFire", "Boolean"},
{"DelayedFireDelay", "Integer"},
{"AltPalette", "Boolean"},
{"PrimaryFireDualOffset", "Boolean"},
{"MidPoint", "Integer"},
{"NormalZAdjust", "Integer"},
{"Recoilless", "Boolean"},
{"PBarrelThickness", "Integer"},
{"SpecialAnimFour", "String"},
{"SpecialAnimFourDamaged", "String"},
{"SpecialAnimFourZAdjust", "Integer"},
{"Reverse", "Boolean"},
{"Palette", "String"},
{"damageFireOffset1", "IEnumerable(Of Integer)"},
{"AddOccupy7", "IEnumerable(Of Integer)"},
{"AddOccupy8", "IEnumerable(Of Integer)"},
{"AddOccupy", "IEnumerable(Of Integer)"},
{"ActiveAnimGarrisoned", "String"},
{"Next", "String"},
{"Warhead", "String"},
{"Damage", "Integer"},
{"WalkSounds", "String"},
{"Idle2Sounds", "String"},
{"CrawlSounds", "String"},
{"FireUpSounds", "String"},
{"Shovel", "IEnumerable(Of Integer)"},
{"Carry", "IEnumerable(Of Integer)"},
{"SecondaryProne", "IEnumerable(Of Integer)"},
{"Die1Sounds", "String"},
{"Die2Sounds", "String"},
{"Fly", "IEnumerable(Of Integer)"},
{"Hover", "IEnumerable(Of Integer)"},
{"FireFly", "IEnumerable(Of Integer)"},
{"Tumble", "IEnumerable(Of Integer)"},
{"AirDeathStart", "IEnumerable(Of Integer)"},
{"AirDeathFalling", "IEnumerable(Of Integer)"},
{"AirDeathFinish", "IEnumerable(Of Integer)"},
{"AnimPalette", "Boolean"},
{"UseLineTrail", "Boolean"},
{"LineTrailColor", "IEnumerable(Of Integer)"},
{"LineTrailColorDecrement", "Integer"},
{"Rotates", "Boolean"},
{"Translucent", "Boolean"},
{"YSortAdjust", "Integer"},
{"UseNormalLight", "Boolean"},
{"ZAdjust", "Integer"},
{"Elasticity", "Single"},
{"MaxXYVel", "Single"},
{"MinZVel", "Single"},
{"ExpireAnim", "String"},
{"DamageRadius", "Integer"},
{"RandomRate", "IEnumerable(Of Integer)"},
{"Bouncer", "Boolean"},
{"Scorch", "Boolean"},
{"SpawnsParticle", "String"},
{"NumParticles", "Integer"},
{"MakeInfantry", "Integer"},
{"TranslucencyDetailLevel", "Integer"},
{"Sticky", "Boolean"},
{"Translucency", "Integer"},
{"Crater", "Boolean"},
{"TiberiumChainReaction", "Boolean"},
{"ForceBigCraters", "Boolean"},
{"Tiled", "Boolean"},
{"Anim", "String"},
{"PsiWarning", "Boolean"},
{"PingPong", "Boolean"},
{"ShouldFogRemove", "Boolean"},
{"IsMeteor", "Boolean"},
{"Spawns", "String"},
{"SpawnCount", "Integer"},
{"IsTiberium", "Boolean"},
{"TiberiumSpawnType", "String"},
{"TiberiumSpreadRadius", "Integer"},
{"AnimLow", "Integer"},
{"AnimHigh", "Integer"},
{"IsAnimatedTiberium", "Boolean"},
{"RandomLoopDelay", "IEnumerable(Of Integer)"},
{"HideIfNoOre", "Boolean"},
{"IsFlamingGuy", "Boolean"},
{"RunningFrames", "Integer"},
{"AnimRate", "Integer"},
{"IsFlat", "Boolean"},
{"DockingOffset4", "IEnumerable(Of Integer)"},
{"DockingOffset5", "IEnumerable(Of Integer)"},
{"TiberiumRadius", "Integer"},
{"Tiberium", "Boolean"},
{"RadLevel", "Integer"},
{"EliteWeapon7FLH", "IEnumerable(Of Integer)"},
{"EliteWeapon8FLH", "IEnumerable(Of Integer)"},
{"EliteWeapon9FLH", "IEnumerable(Of Integer)"},
{"EliteWeapon10FLH", "IEnumerable(Of Integer)"}
}
End Class